### ISSUE TITLE
logback.xml文件冲突.

### ISSUE THREAD

**Issue by siwet** [aliyun/aliyun-log-logback-appender#1]
src/main/resources/  里的logback.xml是不是应该拿掉. 否则会与本地代码的logback.xml文件冲突.

**Comment by brucewu-fly** [comment]
@cntsw , 感谢您的建议。
根据我们的测试，logback会优先使用您本地代码src/main/resources/目录下的`logback.xml`。
如果您的配置文件名不叫`logback.xml`或者文件位于某个其他位置，可以在启动您应用的时候通过JVM参数 `-Dlogback.configurationFile=xxx.xml` 指定。
我们会在之后的版本中考虑您的建议。

**Comment by brucewu-fly** [comment]
@cntsw, 您可以使用 0.1.6 版本的 `aliyun-log-logback-appender`，已经把jar包中的`logback.xml`替换为 `logback-example.xml`

**Comment by siwet** [comment]
可以了. 谢谢
