### ISSUE TITLE
希望提供 slf4j 的appender

### ISSUE THREAD

**Issue by zycgit** [aliyun/aliyun-log-logback-appender#12]

**Comment by chaolee50** [comment]
slf4j是一个日志标准，不提供 appender

**Comment by zycgit** [comment]
项目中使用的是  slf4j api作为日志输出开发接口，底层用的是 logback。
不想修改那么多代码，那么想问一下怎样使用  aliyun-log-logback-appender ？

**Comment by chaolee50** [comment]
[参考-README](https://github.com/aliyun/aliyun-log-logback-appender/blob/master/README_CN.md)
1. maven 工程中引入依赖
2. 修改配置文件

具体配置参数也可[参考-文档
](https://help.aliyun.com/document_detail/68096.html)
