### ISSUE TITLE
如何使用MDC记录requestId，并且在日志服务中可以查到呢？

### ISSUE THREAD

**Issue by aizhimin** [aliyun/aliyun-log-logback-appender#14]
记录请求日志的时候，一般希望通过mdc记录一次请求的各个链路的日志。requestId或者叫traceId。如何配置可以在阿里云日志服务中看到呢？

**Comment by mathcoder23** [comment]
重写这个项目的`LoghubAppender`类，在`appendEvent`事件里面把日志里面的MDC记录取出来push到LogItem里面就行了。
没具体看过xml可以配置不，这种方式肯定可以，自定义字段上传到日志系统同理。

**Comment by chaolee50** [comment]
你好
`    @Test
    public void testLogCommonMessage() {
        MDC.put("THREAD_ID","thread123");
        LOGGER.warn("This is a test common message logged by logback.");
    }`
`<encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger - %msg %X{THREAD_ID}</pattern>
        </encoder>`
![image](https://user-images.githubusercontent.com/25499421/58946012-93350080-87b7-11e9-8516-a04de8d78e97.png)

**Comment by chaolee50** [comment]
你好，
已支持mdc，参考测试用例
1.在logback.xml中
`<mdcFields>aa,bb</mdcFields>`
2.在程序中
`MDC.put("aa","value");`
`MDC.put("bb","value");`

**Comment by aizhimin** [comment]
谢谢  反馈

**Comment by chaolee50** [comment]
已发布新版本，需要稍等几个小时同步
`<version>0.1.15</version>`
