### ISSUE TITLE
打成jar包执行没有反应

### ISSUE THREAD

**Issue by ChenHui15** [aliyun/aliyun-log-logback-appender#19]
放入项目本地执行没问题，打成jar包执行后项目没有反应，也没有任何报错

**Comment by ChenHui15** [comment]
在createProducer方法中的put(projectConfig)没有往下执行，不知道什么原因

**Comment by chaolee50** [comment]
> 在createProducer方法中的put(projectConfig)没有往下执行，不知道什么原因

你好, 看一下是否有包依赖冲突，配置文件的命名有没有问题，是否没有找到配置文件。

**Comment by ChenHui15** [comment]
@chaolee50 是包依赖的问题，已经解决，感谢
