### ISSUE TITLE
能否自己来控制显示那几列日志信息

### ISSUE THREAD

**Issue by xiaolei1004** [aliyun/aliyun-log-logback-appender#2]
现在有一下几个显示的信息，我能不能控制只显示message，或者能不能我自己添加一个或多个列。比如报的这个错误日志是属于那一大分类，添加一列Category
level: 
location: 
message:
thread: 
time: 

还有一个问题：我不可以在配置文件中定义自己显示的message格式吗？？？好像不支持encoder→pattern属性

**Comment by brucewu-fly** [comment]
@xiaolei1004 您好，
1. 目前输出到日志服务中的字段是固定的，字段如下。不支持增加或减少字段。
```
level: ERROR
location: com.aliyun.openservices.log.logback.example.LogbackAppenderExample.main(LogbackAppenderExample.java:18)
message: error log
thread: main
time: 2018-01-02T03:15+0000
__source__: xxx
__topic__: yyy
```
2.我不可以在配置文件中定义自己显示的message格式吗？
目前不支持配置 message 的格式。这个功能会评估下，后续有可能支持。

**Comment by brucewu-fly** [comment]
@xiaolei1004 目前 logback-appender 已经支持定义 encoder，欢迎试用。
```
<encoder>
     <pattern>%d %-5level [%thread] %logger{0}: %msg</pattern>
</encoder>
```

**Comment by brucewu-fly** [comment]
@xiaolei1004 为了保持兼容性，被 encode 的日志会出现在新的字段 `log` 里
