### ISSUE TITLE
如何配合nacos 配置阿里云得secretkey 等等

### ISSUE THREAD

**Issue by MisterChangRay** [aliyun/aliyun-log-logback-appender#30]
建议官方出一个demo

**Comment by popitin593** [comment]
### 我做过这个需求给点思路：

- 使用<springProperty>标签
[https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#profile-specific-configuration](springProperty)
- 2.Nacos支持日志级别的加载时机 nacos.config.bootstrap.log.enable=true
[https://github.com/nacos-group/nacos-spring-boot-project/wiki/spring-boot-0.2.3-%E4%BB%A5%E5%8F%8A-0.1.3-%E7%89%88%E6%9C%AC%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C](spring boot 0.2.3 以及 0.1.3 版本新功能使用手册)
