### ISSUE TITLE
会有死循环打log的情况发生吗

### ISSUE THREAD

**Issue by firebook** [aliyun/aliyun-log-logback-appender#4]
我打个普通的日志，logback appender会发到producer，producer又打印自己的log，这个log通过appender再调用了log producer......循环

**Comment by brucewu-fly** [comment]
@firebook 这是一个非常好的问题，但我们在测试和使用过程中没有遇到这种情况。
如果你遇到了，请把相应的情况详细的描述一下。
另外你可以尝试使用 `<logger name="com.aliyun.openservices.log.producer.inner" level="OFF"/>` 关闭 producer 输出的日志。
