### ISSUE TITLE
ava.lang.NoSuchMethodError: ch.qos.logback.core.encoder.Encoder.encode

### ISSUE THREAD

**Issue by golden-hu** [aliyun/aliyun-log-logback-appender#6]
在com.aliyun.openservices.log.logback.LoghubAppender.appendEvent(LoghubAppender.java:127)
```
item.PushBack("log", new String(this.encoder.encode(eventObject)));
```
中encoder对象没有encode方法，只有一个doEncode方法？
造成错误
我的环境是SpringBoot，1.5.13.RELEASE

**Comment by brucewu-fly** [comment]
你好
我们项目中引用的 logback-core 版本是 1.2.3，你需要确认下你项目中 logback 版本，如果版本过低，尝试在 maven 中手动引入 1.2.3 版本。
```
  <dependency>
         <groupId>ch.qos.logback</groupId>
         <artifactId>logback-core</artifactId>
         <version>1.2.3</version>
   </dependency>
```
