### ISSUE TITLE
请问如果在容器中使用，是否可以省略账号相关的配置？

### ISSUE THREAD

**Issue by eoeac** [aliyun/aliyun-log-logback-appender#7]
请问如果在容器中使用，是否可以省略账号相关的配置？

**Comment by brucewu-fly** [comment]
能否再详细描述下您的需求？

**Comment by zxtwonder** [comment]
请参见https://help.aliyun.com/document_detail/66659.html?spm=5176.11065259.1996646101.searchclickresult.533f232cZLZTWO

使用Logtail进行采集的时候，只需要提供：endpoint、aliyun user id和machine group user defined id。

请问这个LoghubAppender是否可以使用类似方式？

**Comment by brucewu-fly** [comment]
Logback appender 无法支持这种形式
